name: Development

on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run lint
        run: ./gradlew detekt ktlintFormat

      - name: Run all tests
        run: ./gradlew test